### ISSUE TITLE
Add interactive option

### ISSUE THREAD

**Issue by darsain** [darsain/tooltip#10]
Currently, every tooltip is styled with `pointer-events: none`. This removes any possibility for interactive elements.

This styling should be removed, and functionality moved to `interactive` option flag, that would basically do:

```js
this.element.style.pointerEvents = this.options.interactive ? 'all' : 'none';
```

Maybe also `#interactive(boolean)` method.

**Comment by Dillybob92** [comment]
Sweet! I did a dirty trick that's not really intuitive, but gets the job done for my widget system with interactjs.

I simply added 
```.tooltip{
 pointer-events: visible;
}
```
Under where tooltip.css is called (Mind you this is global, and not very intuitive, but for my page it works fine lol).

Then under my data-tooltip attribute, I have html with onclick's to take advantage of the HTML and JS support inside the attributes. Then, upon clickation, for example:

```
data-tooltip='<div class="editb"><span onclick="editwidget({$i}, this)">[Edit]</span> <span onclick="deletewidget({$i})">[X]</span></div>'
```
Then, under editwidget, I call tips.hide(element) so once a user clicks it, it fades out nice! :)

The only issue is, if the user doesn't click these, they're left visible. I'm going to try onmouseout as well with a js function to remove the tips. It still won't be where I want it, but close enough! Here is a gif of it:
![](http://i.gyazo.com/a97cd368f464566767ad4a0d9b1d81ba.gif)

Once you do finish the pointerEvents, this would work like a  **BEAST** for small menus too!

I'll be waiting anxiously, thanks Darsain!
