### ISSUE TITLE
Bower register

### ISSUE THREAD

**Issue by grrseguin** [darsain/tooltip#19]
Hello,

I'd like to use this library in my project with [bower](http://bower.io/docs/creating-packages/#register). Is it possible ?

Bye,

**Comment by darsain** [comment]
Not right now, and I don't think it will be in the future. Tooltip is build on a component/duo ecosystem, and there is no sane way how to make it compatible with others like bower or npm. The change of package manager is also not negotiable. I'll rather not build front-end libraries than deal with bower/npm.

Maybe when I finally get around and set up some standalone UMD build publishing to CDN, you could feed those CDN URLs to `bower.json`, but now that I think about it, I'm not sure if bower can consume those.

Sorry about that.
