### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by applemate** [darsain/tooltip#21]
```
<!DOCTYPE html>
<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script type="text/javascript" src="js/tool.js"></script>
<link rel="stylesheet" type="text/css" href="css/tooltip.css">

<script type="text/javascript">
    $(function(){
        var tip = new Tooltip('Foo bar!');
        tip.position(200, 200).show();
    });

</script>
</head>
<body>
<div class="tooltip"></div>



</body>
</html>
```

the error is body is null

**Comment by darsain** [comment]
I can't make anything out of this. Replicate the issue on jsfiddle or a similar service.

**Comment by jenschr** [comment]
@darsain I think what he meant (without replying you your question) is that when running it like above, it'll crash. The Component package manager is no longer maintained, so he (and I) installed it "manually" by just including the files. 

In "tooltip.js" you have several references to things like body.appendChild(this.element). At that point in time, "body" is null. By changing it to document.body.appendChild(this.element) it worked for me, but I presume that's also not how it's meant to be used?

PS: thanks for building this!

**Comment by ghost** [comment]
ty @jenschr yep, i don't use `require`, so i replaced those, now it works great! [here](https://pastebin.com/raw/hDCzmrKV) is the updated one if anyone needs
