### ISSUE TITLE
Timing: delay and decay

### ISSUE THREAD

**Issue by yankeeinlondon** [darsain/tooltip#22]
Looking at the API there appears to be no way to set timings for hovers. Ideally there would be both "delay" and "decay" time transitions.

**Comment by darsain** [comment]
I don't understand. What timings for hovers?

This is just a library to create and control tooltips. If you are looking for an easy way how to bind tooltips to DOM hover events, you should look at [darsain/tooltips](https://github.com/darsain/tooltips), which consumes this library.

**Comment by yankeeinlondon** [comment]
Yes, hovers is what I'd intended. I guess I didn't understand how you were dividing responsibilities. Fair enough ... I'll close.
