### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by tmcw** [darsain/tooltip#5]
It would be great if we could ingest this plugin via `npm` so it could be use in browserify? The current `package.json` would be great for this, and I'm happy to just use `insert-css` or similar to deal with assets.

---

Tried to `npm install` the tarball, looks like it's not really structured as a package, so this would take more work.

**Comment by cnicodeme** [comment]
If you plan to offer a serious version of your project outside (meaning not an open source of what you do on your side, but a real open source project dedicated to the community), you should (read: "must") make an NPM package out of it.

My reason for this : Your Tooltip plugin is, by far, the best I've seen, not dependant of jQuery and complete.
By releasing it in NPM, you will let thousands of developper use it, and I'm pretty sure you will be on the top for the best Tooltip plugin available.

But hey, that's my opinion ;)

**Comment by ghost** [comment]
2 Year's maybe the npm packaging process have became a bit easier now? Not sure, but either way I agree with cnicodeme, it is the best tooltip library out on the market today (that's free).
